name: Push to Docker hub
run-name: "Push to docker hub: ${{ github.actor }} ğŸš€"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Build-Linux:
    # runs-on: ubuntu-latest
    uses: supergoongaming/sharedWorkflows/.github/workflows/image_build.yml@master
    with:
      image_name: enf3rno/sg_wedding
      build_number: ${{ github.run_number }}
      dockerfile_location: ./Dockerfile
    secrets: inherit

    # steps:
    #   - name: Check out repository code
    #     uses: actions/checkout@v3
    #   - name: Trigger Docker Workflow
    #   - run: echo "ğŸ This job's status is ${{ job.status }}."
